export const AuctionErrorTypes = {
    // Authentication
    LOGIN_FAILED: 'LOGIN_FAILED',
    REGISTRATION_FAILED: 'REGISTRATION_FAILED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

    // Bidding
    BID_TOO_LOW: 'BID_TOO_LOW',
    AUCTION_ENDED: 'AUCTION_ENDED',
    INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
    CANNOT_BID_OWN_ITEM: 'CANNOT_BID_OWN_ITEM',

    // Listings
    INVALID_LISTING: 'INVALID_LISTING',
    LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
    LISTING_CREATE_FAILED: 'LISTING_CREATE_FAILED',
    LISTING_UPDATE_FAILED: 'LISTING_UPDATE_FAILED',

    // Profile
    PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
    PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
    INVALID_PROFILE_DATA: 'INVALID_PROFILE_DATA',

    // Media
    MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
    INVALID_MEDIA_TYPE: 'INVALID_MEDIA_TYPE',
    MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',

    // Network & API
    CONNECTION_ERROR: 'CONNECTION_ERROR',
    API_ERROR: 'API_ERROR',
    REQUEST_FAILED: 'REQUEST_FAILED',
    SERVER_ERROR: 'SERVER_ERROR',

    // Validation
    MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
    INVALID_INPUT_FORMAT: 'INVALID_INPUT_FORMAT',
    INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
    INVALID_ENDPOINT: 'INVALID_ENDPOINT',
};
